image: alpine/edge
secrets:
  - 5f0c9e31-3674-4ca9-8ff8-0891b5d01f00
packages:
  - go
sources:
  - https://github.com/godeezer/lib
tasks:
  - test: |
      cd lib
      go test -v ./...
  - integration-test: |
      [ -f ~/.arl ] || complete-build
      set +x
      . ~/.arl
      set -x
      cd lib
      go test -v ./... -tags integration
